# 기반이 될 Docker 이미지를 선택합니다.
FROM php:7.4-apache

# 필요한 환경 변수를 설정합니다. (예: 데이터베이스 연결 정보 등)
ENV MYSQL_HOST=mysql
ENV MYSQL_DATABASE=moodle
ENV MYSQL_USER=moodleuser
ENV MYSQL_PASSWORD=moodlepassword

# PHP 확장 기능을 설치합니다.
RUN docker-php-ext-install mysqli

# 필요한 추가 패키지를 설치합니다. (예: 필요한 라이브러리, 도구 등)
RUN apt-get update && apt-get install -y \
    git \
    unzip

# Moodle 소스 코드를 가져옵니다.
RUN git clone -b MOODLE_402_STABLE --depth 1 https://github.com/moodle/moodle.git /var/www/html

# Apache 설정 파일을 수정합니다. (필요한 경우)
# COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# 필요한 파일 및 폴더의 권한을 설정합니다.
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html

# 포트를 노출합니다. (기본적으로 80번 포트를 사용합니다)
EXPOSE 80

# 컨테이너가 시작될 때 실행할 명령을 설정합니다.
CMD ["apache2-foreground"]